const SET_DATA = 'SET_DATA';
const GENERATE_CITIES = 'GENERATE_CITIES';
const MAKE_DECISIONS = 'MAKE_DECISIONS';
const GENERATE_NEW_GENERATION = 'GENERATE_NEW_GENERATION';
const OPEN_FORM = 'OPEN_FORM';
const CLOSE_FORM = 'CLOSE_FORM';
const ADD_NEW_LINES = 'ADD_NEW_LINES';
const DRAW_CITIES = 'DRAW_CITIES';
const DRAW_ROUTES = 'DRAW_ROUTES';
const ADD_NEW_ITERATION = 'ADD_NEW_ITERATION';

export
{
    SET_DATA,
    GENERATE_CITIES,
    MAKE_DECISIONS,
    OPEN_FORM,
    CLOSE_FORM,
    GENERATE_NEW_GENERATION,
    ADD_NEW_LINES,
    DRAW_CITIES,
    DRAW_ROUTES,
    ADD_NEW_ITERATION
}
